version: '2'
services:
  nginx:
    container_name: nginx
    image: webdevops/php-nginx-dev:7.3
    depends_on:
      - mysql
    links:
      - mysql:mysql
    restart: always
    expose:
      - "80"
    volumes:
      - "~/Projects/Mobly:/app"
    env_file:
      - "~/Projects/Mobly/docker-compose.env"
    networks:
      net:
        ipv4_address: 172.0.0.2
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - "~/DockerVolumes/Mobly/mysql:/var/lib/mysql"
      - "~/Projects/Mobly/database:/opt/database"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      net:
        ipv4_address: 172.0.0.3
networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
volumes:
  nginx:
  mysql:
  redis:

