version: '2'
services:
  nginx:
    container_name: nginx
    image: webdevops/php-nginx-dev:7.3
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
    restart: always
    expose:
      - "80"
    volumes:
      - "D:/Projects/home/Mobly:/app"
    env_file:
      - "D:/Projects/home/Mobly/docker-compose.env"
    networks:
      net:
        ipv4_address: 172.0.1.2
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - "D:/Projects/storage/Mobly/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      net:
        ipv4_address: 172.0.1.3
  redis:
    container_name: redis
    image: redis
    expose:
      - "6379"
    volumes:
      - "D:/storage/Mobly/redis:/data"
    restart: always
    environment:
      - REDIS_URL=redis://cache
    networks:
      net:
        ipv4_address: 172.0.1.4
networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 172.0.1.0/24
          gateway: 172.0.1.1
volumes:
  nginx:
  mysql:
  redis:

